#!/bin/sh
# gen-on-colors.sh — precompute a contrast-safe foreground ("on-color") for every
# accent slot (base08–base0F), per theme, into home/.chezmoidata/on_colors.toml.
#
# base16 only guarantees the accent slots contrast with base00 (the background),
# NOT the inverse: text placed ON an accent-coloured chip (zellij pills, lualine
# mode block, delta emph, yazi hover) needs a foreground that contrasts with the
# accent — and on light/pastel themes base00 alone isn't enough (e.g. dark text
# on a mid-luminance yellow). So for each slot we pick whichever of base00 / base07
# (the two ends of the mono ramp) contrasts MORE with that slot's colour.
#
# Templates read it as: (index .on_colors .theme).base0A  →  the fg to use when
# base0A is a chip background. Regenerate after theme changes:
#   scripts/gen-on-colors.sh   (theme-audit.sh flags stale/low-contrast pairings)
set -eu
REPO_ROOT=$(CDPATH='' cd "$(dirname "$0")/.." && pwd)
THEMES_DIR="$REPO_ROOT/home/.chezmoidata/themes"
OUT="$REPO_ROOT/home/.chezmoidata/on_colors.toml"

{
	printf '# Generated by scripts/gen-on-colors.sh — DO NOT EDIT BY HAND.\n'
	printf '# Per-theme contrast-safe foreground for chips whose background is an accent\n'
	printf '# slot: on_colors.<theme>.base0X = base00 or base05 (whichever contrasts more\n'
	printf '# with base0X — the bg/fg pair base16 guarantees). See the script header for why.\n'
	for f in "$THEMES_DIR"/*.toml; do
		slug=$(basename "$f" .toml)
		printf '\n[on_colors.%s]\n' "$slug"
		awk '
		function h2d(s,  i, c, val, n) {
			n = 0; s = tolower(s)
			for (i = 1; i <= length(s); i++) {
				c = substr(s, i, 1); val = index("0123456789abcdef", c) - 1
				if (val < 0) val = 0
				n = n * 16 + val
			}
			return n
		}
		function lin(c) { c /= 255; return (c <= 0.04045) ? c / 12.92 : ((c + 0.055) / 1.055) ^ 2.4 }
		function lum(h,  r, g, b) {
			r = h2d(substr(h, 2, 2)); g = h2d(substr(h, 4, 2)); b = h2d(substr(h, 6, 2))
			return 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b)
		}
		function ratio(a, b,  la, lb, t) {
			la = lum(a); lb = lum(b)
			if (la < lb) { t = la; la = lb; lb = t }
			return (la + 0.05) / (lb + 0.05)
		}
		/^base0[0-9A-F] = / { gsub(/"/, "", $3); v[$1] = $3 }
		END {
			split("base08 base09 base0A base0B base0C base0D base0E base0F", slots, " ")
			for (k = 1; k <= 8; k++) {
				s = slots[k]
				on = (ratio(v["base00"], v[s]) >= ratio(v["base05"], v[s])) ? v["base00"] : v["base05"]
				printf "%s = \"%s\"\n", s, on
			}
		}
		' "$f"
	done
} >"$OUT"
printf 'wrote %s (%s themes)\n' "$OUT" "$(find "$THEMES_DIR" -name '*.toml' | wc -l | tr -d ' ')"
